language: perl
sudo: false
matrix:
  include:
    # start the first coverage early so that it starts before everything else
    - perl: "5.20"
      env: COVERAGE=1
    - perl: "5.20"
      env: EUMM_BLEAD=1
    - perl: "5.20"
      env: TEST_INSTALLED=1 # test not from blib but after installing
    - perl: "5.10"
#    - perl: "5.12"
#    - perl: "5.14"
#    - perl: "5.16"
#    - perl: "5.18"
    - perl: "blead"
    - perl: "5.20"
  allow_failures:
    - perl: blead
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - export SPLIT_BUILD=0
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - if [ "$AUTHOR_TESTING" == 1 ]; then cpanm --quiet --notest CPAN::Changes; fi # for author tests (AUTHOR_TESTING is set to true by default by init)
  - if [ "$EUMM_BLEAD" == 1 ]; then cpanm --quiet --notest --dev ExtUtils::MakeMaker; fi
  - build-dist
  - SRC_DIR=$(pwd)
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs coverage prereqs, if enabled
  - prove t/00-report-prereqs.t t/01-checkmanifest.t
  - prove -b -v $SRC_DIR/xt/00-check-changelog.t # run the author test out of the source directory
  # SYSTEM_CORES set by travis-perl-helpers
  - if [ "$SERIAL_BUILD" == 1 ]; then make; else make -j$(( $SYSTEM_CORES * 2 )); fi
before_script:
  - coverage-setup
script:
  - env|sort
  - VERBOSE_FLAG=""; if [ "$TEST_VERBOSE" == 1 ]; then VERBOSE_FLAG="-v"; fi
  - PROVE_FLAG="$VERBOSE_FLAG"; if [ "$TEST_INSTALLED" == 1 ]; then make install clean; mv Basic Basic.x; mv ../Basic ../Basic.x; rm t/01-checkmanifest.t; else PROVE_FLAG="-b $PROVE_FLAG"; fi # clean is to ensure no blib, mv to ensure doesn't think is in repo!
  - if [ "$SERIAL_TESTING" == 1 ]; then prove $PROVE_FLAG $(test-files); else prove --formatter TAP::Formatter::File -j$(test-jobs) $PROVE_FLAG $(test-files); fi
after_success:
  - coverage-report --nogcov
branches:
  except:
    - /^wip\//
    - /^blocked/
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.perl.org#pdl"
    skip_join: true
