language: perl
sudo: false
matrix:
  include:
    # start the first coverage early so that it starts before everything else
    - perl: "5.26"
      env: COVERAGE=1
    - perl: "5.20"
      env: EUMM_BLEAD=1
    - perl: "5.10"
    - perl: "blead"
    - perl: "5.26"
  allow_failures:
    - perl: blead
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - export SPLIT_BUILD=0
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - if [ "$AUTHOR_TESTING" == 1 ]; then cpanm --quiet --notest CPAN::Changes; fi # for author tests (AUTHOR_TESTING is set to true by default by init)
  - if [ "$EUMM_BLEAD" == 1 ]; then cpanm --quiet --notest --dev ExtUtils::MakeMaker; fi
  - build-dist
  - SRC_DIR=$(pwd)
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs coverage prereqs, if enabled
  - prove t/00-report-prereqs.t t/01-checkmanifest.t
  - prove -l -v $SRC_DIR/xt/00-check-changelog.t # run the author test out of the source directory
before_script:
  - coverage-setup
script:
  - env|sort
  - prove --formatter TAP::Formatter::File -j$(test-jobs) -l $(test-files)
after_success:
  - coverage-report
branches:
  except:
    - /^wip\//
    - /^blocked/
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.perl.org#pdl"
    skip_join: true
